// D-I in the browser: which name goes where a person's name goes, and what mark
// stands beside it. The TypeScript half of tui/attest/identity_display.go.
//
// The two halves are held together by a vector file rather than by discipline:
// testdata/attribution.json is generated by the Go implementation and replayed
// against this one (attribution.test.ts). A rule that lived in two languages and
// was only checked by reading is the shape of defect this repository has already
// paid for twice — the `members: null` Welcome and the v1/v2 approval preimage.
//
// # THIS FILE CANNOT PRODUCE A VERIFIED STATE, AND SAYS SO IN ITS TYPES
//
// Verification takes an issuer public key and an evaluation time. A browser
// client has neither: it holds no configuration, and there is no issuer flag on
// a join link. So identityDisplayFor takes no verification result and returns
// only `carried` or `asserted`. The two verified states are in the union because
// the vocabulary is shared and a mark table with holes in it is a mark table
// that gets re-decided, not because this file will ever return them.
//
// That is not a browser limitation to be worked around. It is the same state the
// terminal client is in (tui/ui/app/attribution.go), for the same reason, and
// see the D-J note in join/main.ts for why a browser participant additionally
// cannot HOLD an attested key.

import { fromB64 } from "../crypto/base64";

/** Which of D-I's rows a rendered name is under. Mirrors attest.IdentityDisplayState. */
export type IdentityDisplayState = "verified_named" | "verified_unnamed" | "carried" | "asserted";

/**
 * The identity artifact as it appears on the wire, structurally. Only the fields
 * a display needs are declared; the artifact carries more (serial, subject,
 * signatures, signer_keys, window) and JSON.parse keeps them whether or not this
 * type mentions them.
 */
export interface WireAttestation {
  netherchat_identity?: string;
  /** The SSH SHA-256 fingerprint of the key this statement is about. */
  subject?: string;
  principal?: string;
  display_name?: string;
  roles?: string[];
  issuer?: string;
}

/** One rendered attribution. Mirrors attest.IdentityDisplay. */
export interface IdentityDisplay {
  state: IdentityDisplayState;
  /** What to draw where a person's name goes. */
  name: string;
  principal: string;
  displayName: string;
  issuer: string;
  roles: string[];
  /**
   * The credential is about a different key than the one it arrived on — or the
   * caller named no key to compare against, which is the same thing for a reader.
   * Checkable here, unlike everything else about a credential, because it needs
   * no issuer key and no clock.
   */
  subjectMismatch: boolean;
  /** A human sentence for a detail surface (a tooltip, an aria-label). */
  detail: string;
}

/**
 * The glyph for a state. Deliberately not a checkmark: ✓ in this product means
 * "this client checked something itself", and an issuer attestation is somebody
 * else's statement — so it gets its own shape, filled when checked and hollow
 * when not.
 *
 *   ◆  verified against a pinned issuer key
 *   ◇  a credential arrived; nobody checked it
 *      (nothing) no credential
 */
export function identityDisplayMark(state: IdentityDisplayState): string {
  switch (state) {
    case "verified_named":
    case "verified_unnamed":
      return "◆";
    case "carried":
      return "◇";
    default:
      return "";
  }
}

const UNCHECKED_DETAIL = "a credential accompanied this key and nothing here checked it";

function asserted(name: string): IdentityDisplay {
  return { state: "asserted", name, principal: "", displayName: "", issuer: "", roles: [], subjectMismatch: false, detail: "" };
}

const MALFORMED_DETAIL = "this key arrived with something that is not an identity artifact";

/**
 * Resolve the attribution for one member. `assertedName` is the name the sender
 * chose — the only name that was ever on this wire before. `subjectFpr` is the
 * SSH SHA-256 fingerprint of the key the credential arrived ON (see
 * crypto/identity.ts sshFingerprint). `attestationB64` is
 * WireMember.attestation, or undefined.
 *
 * Bytes that do not decode or do not parse land in `carried`, not `asserted`:
 * something arrived, and rendering the asserted state would be saying nothing
 * did.
 *
 * # THE ONE CHECK THIS PAGE CAN MAKE
 *
 * It cannot verify an issuer signature — no key, no clock — but it CAN ask
 * whether the statement is about the key it arrived on. An attestation is not a
 * secret; anyone who has seen Rosa's identity.json can attach it to their own
 * Hello, and a roster that echoed its claims beside a stranger's key would be
 * repeating a lie it had the means to notice. `subjectMismatch` is set when the
 * subject and the key disagree, or when the caller supplied no key to compare
 * against, and the label says so plainly.
 */
export function identityDisplayFor(
  assertedName: string,
  subjectFpr: string,
  attestationB64?: string,
): IdentityDisplay {
  if (!attestationB64) return asserted(assertedName);

  let parsed: WireAttestation | null = null;
  try {
    parsed = JSON.parse(new TextDecoder().decode(fromB64(attestationB64))) as WireAttestation;
  } catch {
    parsed = null;
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    return {
      state: "carried",
      name: assertedName,
      principal: "",
      displayName: "",
      issuer: "",
      roles: [],
      subjectMismatch: false,
      detail: MALFORMED_DETAIL,
    };
  }
  const subject = parsed.subject ?? "";
  const mismatch = subjectFpr === "" || subject !== subjectFpr;
  return {
    state: "carried",
    name: assertedName,
    principal: parsed.principal ?? "",
    displayName: parsed.display_name ?? "",
    issuer: parsed.issuer ?? "",
    roles: parsed.roles ?? [],
    subjectMismatch: mismatch,
    detail: mismatch
      ? `this credential is about ${subject || "(no subject)"} and arrived on ${subjectFpr || "(no key)"}`
      : UNCHECKED_DETAIL,
  };
}

/**
 * The sentence a roster row carries in its tooltip and its accessible name. A
 * glyph on its own is not readable by a screen reader and not guessable by
 * anyone who has not been told what a diamond means, so the words travel with
 * it everywhere the mark is drawn.
 *
 * It states the claim first and then who checked it, because a reader who sees
 * an enterprise principal with no qualifier supplies one themselves and supplies
 * the wrong one.
 */
export function identityDisplayLabel(d: IdentityDisplay): string {
  if (d.state === "asserted") {
    return "This name is what the sender typed. It is not proven.";
  }
  const claim = d.principal || "an identity";
  const named = d.displayName ? ` (${d.displayName})` : "";
  const roles = d.roles.length ? `, roles ${d.roles.join(", ")}` : "";
  if (d.state === "carried") {
    if (d.subjectMismatch) {
      // Said first and said plainly. This is the one thing about a credential
      // this page actually established, and it is worse than "unchecked": the
      // statement is not about this participant at all.
      return (
        `Carries a credential that is about a DIFFERENT key — ${d.detail}. ` +
        `Whatever it claims (${claim}${named}) says nothing about this person.`
      );
    }
    return (
      `Carries a credential claiming ${claim}${named}${roles}, issued by ${d.issuer || "an unnamed authority"} — ` +
      `not checked here. This page pins no issuer key, so the claim is unverified and the name shown is the one the sender typed.`
    );
  }
  return `Verified: ${claim}${named}${roles}, signed by ${d.issuer}.`;
}
