package engagement

import (
	"fmt"
	"strings"

	"github.com/salehkreiner/netherchat/protocol"
)

// renderTOML produces a commented netherchat.toml for the engagement. The output
// is validated against the real server config parser in the package tests, so it
// always loads cleanly.
func renderTOML(opts Options, rooms []roomSpec, consultants []ConsultantInfo) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# netherchat.toml — generated by `netherchat engagement init` for engagement %q.\n", opts.Name)
	b.WriteString("# This is the relay's source of truth. The relay is BLIND: it never sees\n")
	b.WriteString("# plaintext, identities, or keys. Trust pins and action quorums below are\n")
	b.WriteString("# evaluated CLIENT-SIDE only — the relay never reads them.\n\n")

	b.WriteString("[server]\n")
	fmt.Fprintf(&b, "addr = %s\n\n", tomlString(opts.Addr))

	b.WriteString("# Two-Person Rule: these actions need this many distinct co-signers before they\n")
	b.WriteString("# fire (client-side and cryptographic — the relay only ever sees ciphertext).\n")
	// Key these off the protocol action constants so the generated config matches
	// exactly what the client reads (e.g. break_glass, not break-glass).
	fmt.Fprintf(&b, "[action.%s]\nquorum = %d\n\n", protocol.ActionScuttleAction, opts.Quorum)
	fmt.Fprintf(&b, "[action.%s]\nquorum = %d\n\n", protocol.ActionBreakGlass, opts.Quorum)

	b.WriteString("# --- Rooms (invite-only; each scuttles itself after going idle) ---\n")
	for _, r := range rooms {
		fmt.Fprintf(&b, "[rooms.%s]\n", r.Name)
		b.WriteString("invite_only = true\n")
		b.WriteString("webhook = true\n")
		fmt.Fprintf(&b, "webhook_token = %s\n", tomlString(r.WebhookToken))
		fmt.Fprintf(&b, "ttl = %s\n\n", tomlString(opts.RoomTTL))
		fmt.Fprintf(&b, "[rooms.%s.scuttle]\n", r.Name)
		fmt.Fprintf(&b, "idle_after = %s\n\n", tomlString(opts.IdleScuttle))
	}

	b.WriteString("# --- Trust pins: verify each fingerprint OUT-OF-BAND before trusting it ---\n")
	for _, c := range consultants {
		b.WriteString("[[trust]]\n")
		fmt.Fprintf(&b, "handle = %s\n", tomlString(c.Handle))
		fmt.Fprintf(&b, "fpr = %s\n\n", tomlString(c.Fingerprint))
	}
	return b.String()
}

// renderCompose produces a docker-compose.yml that runs the blind relay against
// the generated netherchat.toml.
func renderCompose(opts Options) string {
	port := portFromAddr(opts.Addr)
	var b strings.Builder
	fmt.Fprintf(&b, "# docker-compose.yml — generated for engagement %q.\n", opts.Name)
	b.WriteString("# Stand up the blind relay:  docker compose up -d\n")
	b.WriteString("services:\n")
	b.WriteString("  relay:\n")
	fmt.Fprintf(&b, "    image: %s\n", opts.Image)
	b.WriteString("    command: [\"--config\", \"/etc/netherchat/netherchat.toml\"]\n")
	b.WriteString("    ports:\n")
	fmt.Fprintf(&b, "      - \"%s:%s\"\n", port, port)
	b.WriteString("    volumes:\n")
	b.WriteString("      - ./netherchat.toml:/etc/netherchat/netherchat.toml:ro\n")
	b.WriteString("    restart: unless-stopped\n")
	return b.String()
}

// renderTrustPins produces a plain handle→fingerprint list for out-of-band
// verification (read the fingerprints aloud and confirm they match).
func renderTrustPins(opts Options, consultants []ConsultantInfo) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Trust pins for engagement %q — verify each OUT-OF-BAND before trusting.\n", opts.Name)
	b.WriteString("# A pinned fingerprint is only as good as the channel you confirmed it over.\n\n")
	for _, c := range consultants {
		fmt.Fprintf(&b, "%-16s %s\n", c.Handle, c.Fingerprint)
	}
	return b.String()
}

// renderReadme produces the package README with deployment and close-out steps,
// and the non-negotiable warnings about the identity files (private keys, no escrow).
func renderReadme(m *Manifest) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Engagement: %s\n\n", m.Name)
	if m.Client != "" {
		fmt.Fprintf(&b, "**Client:** %s  \n", m.Client)
	}
	fmt.Fprintf(&b, "**Created:** %s  \n", m.CreatedAt)
	fmt.Fprintf(&b, "**Relay image:** `%s`  \n\n", m.Relay.Image)

	b.WriteString("A self-contained, end-to-end-encrypted coordination deployment for this\n")
	b.WriteString("engagement. The relay is a **blind** message router — it never sees plaintext,\n")
	b.WriteString("identities, or keys.\n\n")

	b.WriteString("## ⚠️ Handle the identity files as secrets\n\n")
	b.WriteString("`identities/identity-<handle>.json` each contain a **private key**. There is\n")
	b.WriteString("**no escrow and no recovery** — lose the key and you lose access; that is the\n")
	b.WriteString("design. Deliver each file to its owner over a secure channel, and remove your\n")
	b.WriteString("copy afterward. Better still, have each consultant bring their own key and\n")
	b.WriteString("replace the generated pin in `netherchat.toml` with theirs.\n\n")

	b.WriteString("## 1. Stand up the relay\n\n")
	b.WriteString("```sh\ndocker compose up -d\n```\n\n")

	b.WriteString("## 2. Connect (each consultant)\n\n")
	b.WriteString("```sh\n")
	b.WriteString("netherchat connect ws://RELAY_HOST:" + m.Relay.Port + " \\\n")
	b.WriteString("  --identity identities/identity-<you>.json \\\n")
	b.WriteString("  --config netherchat.toml \\\n")
	if len(m.Rooms) > 0 {
		b.WriteString("  --room " + m.Rooms[0] + "\n")
	} else {
		b.WriteString("  --room ops\n")
	}
	b.WriteString("```\n\n")
	b.WriteString("Confirm every fingerprint in `trust-pins.txt` **out of band** before trusting it.\n\n")

	b.WriteString("## 3. Close out\n\n")
	b.WriteString("Drop the sealed records produced in-room (`/seal` → `record.json`) into the\n")
	b.WriteString("`records/` folder, then generate the consolidated, offline-verifiable report:\n\n")
	fmt.Fprintf(&b, "```sh\nnetherchat engagement close %s\n```\n\n", m.Name)

	b.WriteString("## Package contents\n\n")
	b.WriteString("| Path | What |\n|---|---|\n")
	b.WriteString("| `netherchat.toml` | relay config: rooms, trust pins, action quorums |\n")
	b.WriteString("| `docker-compose.yml` | the blind relay, ready to run |\n")
	b.WriteString("| `identities/` | one private identity per consultant (deliver securely) |\n")
	b.WriteString("| `trust-pins.txt` | handle → fingerprint, for out-of-band verification |\n")
	b.WriteString("| `records/` | drop sealed records here before closing |\n")
	b.WriteString("| `engagement.json` | machine-readable manifest |\n")
	return b.String()
}

// recordsReadme is dropped into records/ to explain the folder's purpose.
const recordsReadme = `# Sealed records

Drop the sealed records produced in-room here (run ` + "`/seal`" + ` in a war room to
write a ` + "`record.json`" + `). ` + "`netherchat engagement close`" + ` reads every
` + "`*.json`" + ` in this folder, re-verifies it offline, and rolls them into one
consolidated close report.

These files contain only the decisions and actions that were explicitly sealed —
never the ephemeral discussion.
`

// tomlString renders s as a TOML basic string, escaping the only two characters
// that matter inside one (backslash and double-quote).
func tomlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
